# This file was introduced to define flags for codecov. Flags are necessary for generating separate
# coverage reports in a multi-project build. See https://docs.codecov.io/docs/flags
coverage:
  status:
    project:
      default:
        target: auto
      protocol:
        target: auto
        flags:
          - protocol
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
flags:
  protocol:
    paths:
      - protocol
    carryforward: false
