name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PARALLEL_SPEC_EXECUTION: false
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: sbt coverage test coverageReport

    - name: Coverage Report
      uses: codecov/codecov-action@v1

    - name: Generate Scaladoc
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        sbt unidoc
        mkdir -p target/site/api
        mv target/scala-2.13/unidoc/* target/site/api

    - name: Publish Site
      if: startsWith(github.ref, 'refs/tags/v')
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/site
