name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: sbt coverage test coverageReport

    - name: Coverage Report
      uses: codecov/codecov-action@v1

    - name: Publish Site
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
      run: sbt ghpagesPushSite
